export const GET_STUDENT = 'GET_STUDENT'
export const STUDENT_ERROR = 'STUDENT_ERROR'

export const GET_STUDENT_BOOK = 'GET_STUDENT_BOOK'
export const STUDENT_BOOK_ERROR = 'STUDENT_BOOK_ERROR'

export const GET_CLASSROOM = 'GET_CLASSROOM'
export const CLASSROOM_ERROR = 'CLASSROOM_ERROR'

export const GET_POPUPS = 'GET_POPUPS'
export const POPUPS_ERROR = 'POPUPS_ERROR'

export const GET_CLASSLIST = 'GET_CLASSLIST'
export const CLASSLIST_ERROR = 'CLASSLIST_ERROR'

export const GET_TIMESTAMPS = 'GET_TIMESTAMPS'
export const TIMESTAMPS_ERROR = 'TIMESTAMPS_ERROR'

export const GET_BOOKLIST = 'GET_BOOKLIST'
export const BOOKLIST_ERROR = 'BOOKLIST_ERROR'

export const GET_CLASSROOM_STUDENTS = 'GET_CLASSROOM_STUDENTS'
export const SET_CLASSROOM_STUDENTS = 'SET_CLASSROOM_STUDENTS'
export const CLEAR_CLASSROOM_STUDENTS = 'CLEAR_CLASSROOM_STUDENTS'
export const CLASSROOM_STUDENTS_ERROR = 'CLASSROOM_STUDENTS_ERROR'
